# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='image/')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
