# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='editor',
            new_name='user',
        ),
    ]
